spring:
  datasource:
    url: jdbc:postgresql://tax-db.clmbnsht10eo.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka