spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_db
    username: postgres
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka