pipeline {
  agent any

  stages {
    stage('Download sources'){
      steps{
        checkout scm
      }
    }

    stage("Build") {
      steps {
        sh "cd card-insurance/client/ && chmod +x gradlew && ./gradlew build && ./gradlew flywaymigrate -i"
      }
    }

    stage("Send Zip to S3") {
      steps {
        sh "cd card-insurance/client/client-api/build/libs && aws s3 rm s3://card-insurance-storage/client-api.jar && aws s3 cp --acl public-read client-api.jar s3://card-insurance-storage"
      }
    }

    stage("Run Java Application") {
      steps {
        script {
            sshagent(credentials : ['tax-devops-server-deploy']) {
                sh "echo Connecting to the remote server"
                sh '''ssh -t -t ubuntu@ip-10-0-16-13.ec2.internal -o StrictHostKeyChecking=no << EOF
                #!/bin/bash
                echo Connected to Client Service App
                pkill -9 -f java
                rm -f client-api.jar
                wget https://card-insurance-storage.s3.amazonaws.com/client-api.jar
                java -jar -Dspring.profiles.active=prod client-api.jar &
                exit
                EOF'''
            }
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}