package com.bmarques.tax.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.bmarques.tax.LocalDateConverter;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "invoice")
public class InvoiceEntity {

    private String id;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate installmentDate;

    @DynamoDBAttribute
    private String document;

    @DynamoDBAttribute
    private String client;

    @DynamoDBAttribute
    private Double value;

    @DynamoDBHashKey(attributeName = "invoiceId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
}
