pipeline {
  agent any

  stages {
    stage('Download sources'){
      steps{
        checkout scm
      }
    }

    stage("Build") {
      steps {
        sh "pwd && cd tax-calculate/tax && chmod +x gradlew && ./gradlew buildZip"
      }
    }

    stage("Send Zip to S3") {
      steps {
        sh "cd tax-calculate/tax/build/distributions && aws s3 rm s3://tax-lambda-jar-storage/tax-0.0.1-SNAPSHOT.zip && aws s3 cp tax-0.0.1-SNAPSHOT.zip s3://tax-lambda-jar-storage"
      }
    }

    stage("Update lambda") {
      steps {
        sh "aws lambda update-function-code --function-name tax-lambda --s3-bucket tax-lambda-jar-storage --s3-key tax-0.0.1-SNAPSHOT.zip"
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}